name: Auto Merge PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-on-comment:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, 'merge')
    
    steps:
    - name: Merge PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (github.event.comment.body.trim().toLowerCase() === 'merge') {
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: github.event.issue.number,
              merge_method: 'squash'
            });
            console.log('✅ PR merged!');
          }
