name: Auto Merge on PR Comment

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "PR exists: ${{ github.event.issue.pull_request }}"
          echo "Comment body: '${{ github.event.comment.body }}'"

      - name: Merge PR if comment is 'merge'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Ensure this is a PR comment
            if (!context.payload.issue?.pull_request) {
              console.log("Not a PR comment; skipping.");
              return;
            }

            // Normalize comment text
            const comment = context.payload.comment.body.trim().toLowerCase();
            if (comment !== "merge") {
              console.log("Comment is not 'merge'; skipping.");
              return;
            }

            const pr_number = context.payload.issue.number;
            console.log(`Merging PR #${pr_number} into its base branch...`);

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: "squash",
              commit_title: `Auto-merged PR #${pr_number}`,
              commit_message: "Merged via comment 'merge'"
            });

            console.log(`PR #${pr_number} merged successfully.`);
