name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  process-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Determine PR number
      id: get_pr
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let pr_number = null;

          if (github.event_name === 'pull_request' && github.event.pull_request) {
            pr_number = github.event.pull_request.number;
          } 
          else if (github.event_name === 'issue_comment' && github.event.issue.pull_request) {
            // عند التعليق على PR
            pr_number = github.event.issue.number;
          }

          if (!pr_number) {
            console.log("This event is not a PR-related event. Skipping workflow.");
            core.setOutput('pr_number', '');
          } else {
            console.log("Found PR number: " + pr_number);
            core.setOutput('pr_number', pr_number.toString());
          }
          
          return pr_number;
      result-encoding: string

    - name: Check if PR number exists
      id: check_pr
      run: |
        if [ -z "${{ steps.get_pr.outputs.pr_number }}" ]; then
          echo "pr_exists=false" >> $GITHUB_OUTPUT
          echo "No PR number found. Exiting workflow."
        else
          echo "pr_exists=true" >> $GITHUB_OUTPUT
          echo "PR number: ${{ steps.get_pr.outputs.pr_number }}"
        fi

    - name: Process PR (if exists)
      if: steps.check_pr.outputs.pr_exists == 'true'
      run: |
        echo "Processing PR #${{ steps.get_pr.outputs.pr_number }}"
        # Add your PR processing logic here

    - name: Skip workflow
      if: steps.check_pr.outputs.pr_exists == 'false'
      run: |
        echo "Skipping workflow as this is not a PR-related event"
