name: Auto Merge PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-on-comment:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, 'merge')
    
    steps:
    - name: Merge PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            const commentBody = github.event.comment.body.trim().toLowerCase();
            if (commentBody === 'merge') {
              const prNumber = github.event.issue.number;
              
              console.log(`Merging PR #${prNumber}...`);
              
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'squash'
              });
              
              console.log('✅ PR merged successfully!');
            }
          } catch (error) {
            console.error('❌ Merge failed:', error.message);
            core.setFailed(`Merge failed: ${error.message}`);
          }
