name: Auto Merge on Comment or PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR triggered by comment
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request != null && contains(github.event.comment.body, 'merge')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = context.issue.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: "squash"
            });

      - name: Merge PR triggered by PR event
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = github.event.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: "squash"
            });

      - name: Comment success
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = github.event_name == 'issue_comment' ? context.issue.number : github.event.pull_request.number;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: "✅ PR merged successfully by automation."
            });

      - name: Comment failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = github.event_name == 'issue_comment' ? context.issue.number : github.event.pull_request.number;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: "❌ Auto-merge failed. Check Actions logs for details."
            });
