name: Auto Merge PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-on-comment:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, 'recheck')
    
    steps:
    - name: Merge PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (github.event.comment.body.trim().toLowerCase() === 'recheck') {
            console.log('✅ PR merged!');
          }
