name: Auto Merge on Comment or PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Determine PR number
        id: get_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let pr_number;
            if (github.event_name === 'issue_comment' && github.event.issue.pull_request) {
              pr_number = context.issue.number;
            } else if (github.event_name === 'pull_request' && github.event.pull_request) {
              pr_number = github.event.pull_request.number;
            } else {
              core.setFailed("No PR number found for this event.");
            }
            return pr_number;

      - name: Merge PR
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.get_pr.outputs.result }};
            console.log("Merging PR #" + pr_number);
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr_number,
              merge_method: "squash"
            });

      - name: Comment result
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ steps.get_pr.outputs.result }};
            const message = success() 
              ? "✅ PR merged successfully by automation." 
              : "❌ Auto-merge failed. Check Actions logs for details.";
            if (pr_number) {
              await github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr_number,
                body: message
              });
            }
