name: PR Quality Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  code-quality:
    name: Code Formatting and Compatibility
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'recheck'))
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pyright

      - name: Check code formatting with Black
        run: black --check .

      - name: Check Python 3.12 compatibility with Pyright
        run: pyright --pythonversion 3.12
