name: PR Quality Checks

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  code-quality:
    name: Code Formatting and Compatibility
    if: contains(github.event.pull_request.labels.*.name, 'check') || (github.event_name == 'issue_comment' && github.event.comment.body == 'recheck')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pyright yamllint

      - name: Check code formatting with Black
        run: black --check .

      - name: Lint all YAML files
        run: yamllint . --strict

      - name: Check Python 3.12 compatibility with Pyright
        run: pyright --pythonversion 3.12
