name: Recheck

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: read
  contents: read

jobs:
  merge-on-comment:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != '' &&
      contains(github.event.comment.body, 'recheck')
    
    steps:
    - name: Recheck
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (github.event.comment.body.trim().toLowerCase() === 'recheck') {
  
            console.log('✅ recheck is detected !');
          }
